#!/bin/bash
#   Copyright 2023 Brian Stucker
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


# Check the script is being run by root user)
check_run_user() {
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
}

# Create User and group - Create Directory and Symbolic Link
check_if_exist_user() {
egrep -i "^sysop:" /etc/passwd;
   if [ $? -eq 0 ]; then
      echo "User SYSOP exists."
      userdel sysop
   fi
}

check_if_exist_group() {
egrep -i "^spider" /etc/group;
    if [ $? -eq 0 ]; then
        echo "Group SPIDER exists."
        groupdel spider
    fi
}

clean() {
  # Stop and remove dxspider containers
  docker container stop $( sudo docker ps -a | grep dxspider-deployment | awk '{ print $1 }' ) 2> /dev/null
  docker container stop $( sudo docker ps -a | grep dxspider-deployment | awk '{ print $1 }' ) 2> /dev/null

  # Remove all of our dxspider images
  sudo docker image rm -f $(sudo docker images | grep dxspider-deployment | awk '{ print $3 }') 2> /dev/null

  # Prune
  sudo docker system prune
  sudo docker volume prune
}

main() {
 check_run_user
 clean

 sudo docker container ls
 sudo docker images
 sudo docker volume ls
}

main

exit 0
